---
name: wordswithletters
title: Word with letters
email: marketing@wordswithletters.org
address: Noida, Delhi
phone: ''
tagline: wordswithletters - Fifteen letters! Enough to get the longest word in the English Dictionary.
description: wordswithletters provides Fifteen letters! Enough to get the longest word in the English Dictionary.
baseurl: ''
permalink: /blog/:title
theme: word-games-theme
url: https://wordswithletters.org
siteurl: https://wordswithletters.org
alternateName: wordswithletters
# show_allow_ad_blocker_pop: true
# adBlockerClose: true
# adspopuptitle: Wordswithletters.org
facebook_username: https://www.facebook.com/wordswith.lettersorg/
twitter_username: https://twitter.com/wordswithlette1
linkedin_username: https://www.linkedin.com/in/wordswithlettersorg/
instagram_username: https://www.instagram.com/wordswithlettersorg/
MonumetricID: ezoic_config_true
favicon: /assets/images/wordswithletters-logo.png
logo: /assets/images/wordswithletters-logo.png
paginate: '12'
paginate_path: '/blog/page:num/'
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
disqus:
  shortname: wordswithletters
hero: product_fixed_image
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
getform_id:
mailchimp:
  user-id:
  list-id:
copyright_text: Copyright © 2022 All rights reserved to
company_url: https://wordswithletters.org/
production_google_analytics: 'UA-179965937-8'
development_google_analytics: ''
google_site_verification:
bing_site_verification:
yandex_site_verification:
naver_site_verification:
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:
timezone:
after: ruby hello.rb
