[build]
  functions = "functions" 

 [[redirects]]
  from = "/advancedFilter/*"
  to = "https://wordcollections.netlify.app/.netlify/functions/:splat"
  force = true
  status = 200
[[redirects]]
  from = "/filterData"
  to = "https://wordcollections.netlify.app/filterData.json"
  force = true
  status = 200