[build]
  functions = "functions" 
  
  [[redirects]]
  from = "/advancedFilter/*"
  to = "https://collection-pages.netlify.app/.netlify/functions/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/filterData"
  to = "https://collection-pages.netlify.app/filterData.json"
  force = true
  status = 200





